### ISSUE TITLE
[hyunahOh] 과제 문제 리스트

### ISSUE THREAD

**Issue by hyunahOh** [frontend-algo/into-the-deep#9]
Array

- [ ] [Two Sum](https://algorithm.prettylog.com/daily-algorithms/study/problems/1.-two-sums) - https://leetcode.com/problems/two-sum/
- [ ]  [Best Time to Buy and Sell Stock ](https://algorithm.prettylog.com/daily-algorithms/study/problems/2.-best-time-to-buy-and-sell-stock)- https://leetcode.com/problems/best-time-to-buy-and-sell-stock/ ✳️
- [ ]  [Contains Duplicate](https://algorithm.prettylog.com/daily-algorithms/study/problems/3.-contains-duplicate) - https://leetcode.com/problems/contains-duplicate/
- [ ]  [Product of Array Except Self](https://algorithm.prettylog.com/daily-algorithms/study/problems/4.-238.-product-of-array-except-self) - https://leetcode.com/problems/product-of-array-except-self/ ✳️
- [ ]  [Maximum Subarray - https://leetcode.com/problems/maximum-subarray/](https://algorithm.prettylog.com/daily-algorithms/study/problems/5.-53.-maximum-subarray)
- [ ]  [Maximum Product Subarray](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/maximum-product-subarray/
- [ ]  [Find Minimum in Rotated Sorted Array](https://algorithm.prettylog.com/daily-algorithms/study/problems/7.-153.-find-minimum-in-rotated-sorted-array) - https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/
- [ ]  [Search in Rotated Sorted Array](https://algorithm.prettylog.com/daily-algorithms/study/problems/8.-33.-search-in-rotated-sorted-array) - https://leetcode.com/problems/search-in-rotated-sorted-array/
- [ ]  [3Sum](https://algorithm.prettylog.com/daily-algorithms/study/problems/9.-15.-3sum) - https://leetcode.com/problems/3sum/
- [ ]  [Container With Most Water](https://algorithm.prettylog.com/daily-algorithms/study/problems/10.-11.-container-with-most-water) - https://leetcode.com/problems/container-with-most-water/

Binary

- [ ] [Sum of Two Integers](https://algorithm.prettylog.com/daily-algorithms/study/problems/11.-371.-sum-of-two-integers) - https://leetcode.com/problems/sum-of-two-integers/
- [ ]  [Number of 1 Bits](https://algorithm.prettylog.com/daily-algorithms/study/problems/12.-191.-number-of-1-bits) - https://leetcode.com/problems/number-of-1-bits/
- [ ]  [Counting Bits](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/counting-bits/
- [ ]  [Missing Number](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/missing-number/
- [ ]  [Reverse Bits](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/reverse-bits/

Dynamic Programming

- [ ]  [Climbing Stairs](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/climbing-stairs/
- [ ]  [Coin Change](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/coin-change/
- [ ]  [Longest Increasing Subsequence](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/longest-increasing-subsequence/
- [ ]  [Longest Common Subsequence](https://github.com/frontend-algo/into-the-deep/issues/1) -
- [ ]  [Word Break Problem](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/word-break/
- [ ]  [Combination Sum](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/combination-sum-iv/
- [ ]  [House Robber](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/house-robber/
- [ ]  [House Robber II](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/house-robber-ii/
- [ ]  [Decode Ways](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/decode-ways/
- [ ]  [Unique Paths](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/unique-paths/
- [ ]  [Jump Game](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/jump-game/

Graph

 

- [ ] [Clone Graph](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/clone-graph/
- [ ]  [Course Schedule](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/course-schedule/
- [ ]  [Pacific Atlantic Water Flow](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/pacific-atlantic-water-flow/
- [ ]  [Number of Islands](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/number-of-islands/
- [ ]  [Longest Consecutive Sequence](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/longest-consecutive-sequence/
- [ ]  [Alien Dictionary (Leetcode Premium)](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/alien-dictionary/
- [ ]  [Graph Valid Tree (Leetcode Premium) ](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/graph-valid-tree/
- [ ]  [Number of Connected Components in an Undirected Graph (Leetcode Premium)](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/

Interval

- [ ]  [Insert Interval ](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/insert-interval/
- [ ]  [Merge Intervals](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/merge-intervals/
- [ ]  [Non-overlapping Intervals](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/non-overlapping-intervals/
- [ ]  [Meeting Rooms (Leetcode Premium)](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/meeting-rooms/
- [ ]  [Meeting Rooms II (Leetcode Premium)](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/meeting-rooms-ii/

Linked List

- [ ]  [Reverse a Linked List](https://algorithm.prettylog.com/daily-algorithms/study/problems/linked-list/206.-reverse-linked-list) - https://leetcode.com/problems/reverse-linked-list/ ✳️
- [ ]  [Detect Cycle in a Linked List](https://algorithm.prettylog.com/daily-algorithms/study/problems/linked-list/141.-linked-list-cycle) - https://leetcode.com/problems/linked-list-cycle/
- [ ]  [Merge Two Sorted Lists](https://algorithm.prettylog.com/daily-algorithms/study/problems/linked-list/21.-merge-two-sorted-lists) - https://leetcode.com/problems/merge-two-sorted-lists/
- [ ]  [Merge K Sorted Lists](https://algorithm.prettylog.com/daily-algorithms/study/problems/linked-list/23.-merge-k-sorted-lists) - https://leetcode.com/problems/merge-k-sorted-lists/
- [ ]  [Remove Nth Node From End Of List](https://algorithm.prettylog.com/daily-algorithms/study/problems/linked-list/19.-remove-nth-node-from-end-of-list) - https://leetcode.com/problems/remove-nth-node-from-end-of-list/
- [ ]  [Reorder List](https://algorithm.prettylog.com/daily-algorithms/study/problems/linked-list/143.-reorder-list) - https://leetcode.com/problems/reorder-list/

Matrix

- [ ]  [Set Matrix Zeroes](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/set-matrix-zeroes/
- [ ]  [Spiral Matrix](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/spiral-matrix/
- [ ]  [Rotate Image](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/rotate-image/
- [ ]  [Word Search ](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/word-search/

String

 

- [ ] [Longest Substring Without Repeating Characters](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/longest-substring-without-repeating-characters/
- [ ]  [Longest Repeating Character Replacement ](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/longest-repeating-character-replacement/
- [ ]  [Minimum Window Substring](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/minimum-window-substring/
- [ ]  [Valid Anagram](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/valid-anagram/
- [ ]  [Group Anagrams ](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/group-anagrams/
- [ ]  [Valid Parentheses](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/valid-parentheses/
- [ ]  [Valid Palindrome](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/valid-palindrome/
- [ ]  [Longest Palindromic Substring](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/longest-palindromic-substring/
- [ ]  [Palindromic Substrings](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/palindromic-substrings/
- [ ]  [Encode and Decode Strings (Leetcode Premium)](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/encode-and-decode-strings/

Tree

- [ ]  [Maximum Depth of Binary Tree](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/maximum-depth-of-binary-tree/
- [ ]  [Same Tree](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/same-tree/
- [ ]  [Invert/Flip Binary Tree](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/invert-binary-tree/
- [ ]  [Binary Tree Maximum Path Sum](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/binary-tree-maximum-path-sum/
- [ ]  [Binary Tree Level Order Traversal](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/binary-tree-level-order-traversal/
- [ ]  [Serialize and Deserialize Binary Tree](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/serialize-and-deserialize-binary-tree/
- [ ]  [Subtree of Another Tree](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/subtree-of-another-tree/
- [ ]  [Construct Binary Tree from Preorder and Inorder Traversal](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/
- [ ]  [Validate Binary Search Tree](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/validate-binary-search-tree/
- [ ]  [Kth Smallest Element in a BST](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/kth-smallest-element-in-a-bst/
- [ ]  [Lowest Common Ancestor of BST](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/
- [ ]  [Implement Trie (Prefix Tree)](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/implement-trie-prefix-tree/
- [ ]  [Add and Search Word ](https://github.com/frontend-algo/into-the-deep/issues/1)- https://leetcode.com/problems/add-and-search-word-data-structure-design/
- [ ]  [Word Search II](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/word-search-ii/

Heap

 

- [ ] [Merge K Sorted Lists](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/merge-k-sorted-lists/
- [ ]  [Top K Frequent Elements](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/top-k-frequent-elements/
- [ ]  [Find Median from Data Stream](https://github.com/frontend-algo/into-the-deep/issues/1) - https://leetcode.com/problems/find-median-from-data-stream/
